-- Migration 081: Per-user supply order codes — auto-generated 4 digits, visible on profile.
--
-- Replaces the prior hashed-secret model. The code is shown to its owner on
-- their profile, so it needs to be stored as plaintext. (A 4-digit hash is
-- trivially brute-forced from any leaked hash anyway — uniqueness, not
-- secrecy, is what matters here.)
--
-- One row per user. Code is unique across users so it can identify the
-- authorizer in audit. Codes are generated lazily by get_my_supply_order_code()
-- on first request, and can be rotated by regenerate_my_supply_order_code().
--
-- The previous profiles.supply_order_code_hash column is left in place but
-- unused — drop it in a follow-up migration once you're confident.
--
-- Apply manually after review.

BEGIN;

CREATE TABLE IF NOT EXISTS public.supply_order_codes (
  user_id       uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  code          text NOT NULL UNIQUE CHECK (code ~ '^[0-9]{4}$'),
  generated_at  timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.supply_order_codes IS
  'Per-user 4-digit code used to authorize large supply orders. Auto-generated by RPC; visible to its owner on their profile.';

ALTER TABLE public.supply_order_codes ENABLE ROW LEVEL SECURITY;

-- A user can read their own row. Writes only via the SECURITY DEFINER RPCs below.
DROP POLICY IF EXISTS supply_order_codes_self_read ON public.supply_order_codes;
CREATE POLICY supply_order_codes_self_read ON public.supply_order_codes
  FOR SELECT
  TO authenticated
  USING (user_id = auth.uid());

-- ---------------------------------------------------------------------------
-- get_my_supply_order_code()
--   Returns the caller's code, generating one if missing.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.get_my_supply_order_code()
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id  uuid := auth.uid();
  v_code     text;
  v_attempts int  := 0;
BEGIN
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'not authenticated';
  END IF;

  SELECT code INTO v_code
  FROM public.supply_order_codes
  WHERE user_id = v_user_id;
  IF v_code IS NOT NULL THEN
    RETURN v_code;
  END IF;

  LOOP
    v_attempts := v_attempts + 1;
    v_code := lpad((floor(random() * 10000))::int::text, 4, '0');
    IF NOT EXISTS (SELECT 1 FROM public.supply_order_codes WHERE code = v_code) THEN
      INSERT INTO public.supply_order_codes (user_id, code) VALUES (v_user_id, v_code);
      RETURN v_code;
    END IF;
    IF v_attempts > 100 THEN
      RAISE EXCEPTION 'could not allocate a unique 4-digit code after 100 attempts';
    END IF;
  END LOOP;
END;
$$;

-- ---------------------------------------------------------------------------
-- regenerate_my_supply_order_code()
--   Rotates the caller's code. Use when a code might have been seen.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.regenerate_my_supply_order_code()
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id  uuid := auth.uid();
  v_code     text;
  v_attempts int  := 0;
BEGIN
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'not authenticated';
  END IF;

  LOOP
    v_attempts := v_attempts + 1;
    v_code := lpad((floor(random() * 10000))::int::text, 4, '0');
    IF NOT EXISTS (
      SELECT 1 FROM public.supply_order_codes
      WHERE code = v_code AND user_id <> v_user_id
    ) THEN
      INSERT INTO public.supply_order_codes (user_id, code, generated_at)
      VALUES (v_user_id, v_code, now())
      ON CONFLICT (user_id) DO UPDATE
        SET code = excluded.code, generated_at = excluded.generated_at;
      RETURN v_code;
    END IF;
    IF v_attempts > 100 THEN
      RAISE EXCEPTION 'could not allocate a unique 4-digit code after 100 attempts';
    END IF;
  END LOOP;
END;
$$;

-- ---------------------------------------------------------------------------
-- verify_supply_order_code(p_code text)
--   Replaces the prior hash-based version. Returns true if the supplied code
--   matches the caller's row.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.verify_supply_order_code(p_code text)
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.supply_order_codes
    WHERE user_id = auth.uid() AND code = p_code
  );
$$;

REVOKE ALL ON FUNCTION public.get_my_supply_order_code()        FROM anon, public;
REVOKE ALL ON FUNCTION public.regenerate_my_supply_order_code() FROM anon, public;
REVOKE ALL ON FUNCTION public.verify_supply_order_code(text)    FROM anon, public;
GRANT EXECUTE ON FUNCTION public.get_my_supply_order_code()        TO authenticated;
GRANT EXECUTE ON FUNCTION public.regenerate_my_supply_order_code() TO authenticated;
GRANT EXECUTE ON FUNCTION public.verify_supply_order_code(text)    TO authenticated;

COMMIT;
