-- Create the missing notifications that should have been generated by the triggers
INSERT INTO user_notifications (user_id, type, title, message, urgency, action_url, related_id, metadata, created_at)
VALUES 
  (
    '4fbaf107-c81b-4442-af1d-cbe965736fe3', 
    'new_assignment', 
    'New Room Assignment', 
    'You have been assigned to 1121 (work_location)',
    'medium',
    '/dashboard',
    'a1e127e9-6c91-4b47-966a-b4d4c9fe3a18',
    '{"assignment_id": "62cdf289-36a5-41a0-8b64-aa26467837ff", "room_id": "a1e127e9-6c91-4b47-966a-b4d4c9fe3a18", "assignment_type": "work_location", "is_primary": false}',
    '2025-07-16 02:54:31.702612+00'
  ),
  (
    '4fbaf107-c81b-4442-af1d-cbe965736fe3',
    'new_assignment',
    'New Room Assignment', 
    'You have been assigned to 1112 as your primary office',
    'high',
    '/dashboard', 
    '223b305c-d463-485c-a329-017beb76a2fa',
    '{"assignment_id": "c47cb056-8d67-40a5-8df5-6638cc2357e8", "room_id": "223b305c-d463-485c-a329-017beb76a2fa", "assignment_type": "primary_office", "is_primary": true}',
    '2025-07-16 02:54:08.716886+00'
  );